export const constCountries =[
    "Argentina",
    "Bolivia",
    "Brasil",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Ecuador",
    "Estados Unidos",
    "El Salvador",
    "España",
    "Guatemala",
    "Guayana",
    "Haití",
    "Honduras",
    "Jamaica",
    "México",
    "Nicaragua",
    "Paraguay",
    "Panamá",
    "Perú",
    "República Dominicana",
    "Uruguay",
    "Venezuela"
]